blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.FlaxIndexView.as_view(), name='index'),
]

engagement/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'suggestion/create$', views.SuggestionCreateView.as_view(), name='suggestion_create'),
    url(r'image/add', views.ImageCreateView.as_view(), name='image_create'),
    url(r'gallery', views.ImageListView.as_view(), name='image_list'),
]

flax/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls', namespace='blog')),
    url(r'^user-engagement/', include('engagement.urls', namespace='engagement')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

engagement/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone


class Suggestion(models.Model):
    username = models.CharField(max_length=155, unique=True, )
    your_suggestion = models.TextField(null=False, blank=False, help_text='brief info.')
    timestamp = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-id', )

    def __str__(self):
        return self.username


class Image(models.Model):
    pic = models.ImageField(verbose_name='Image', blank=True, null=True)
    caption = models.CharField(max_length=155)

engagement/forms.py
from django import forms
from django.forms.models import modelformset_factory
from .models import Image, Suggestion


class SuggestionForm(forms.ModelForm):
    class Meta:
        model = Suggestion
        exclude = ('timestamp',)


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = '__all__'

    def save(self, commit=True):
        obj = super(ImageForm, self).save(commit=False)
        obj.save()
        return obj

blog/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from engagement.forms import ImageForm, SuggestionForm
from engagement.models import Suggestion

from flax_views.mixins import PageTitleMixin


class FlaxIndexView(PageTitleMixin, TemplateView):
    template_name = 'blog/index.html'
    title = 'index'

    def get_context_data(self, **kwargs):
        c = super(FlaxIndexView, self).get_context_data(**kwargs)
        c['suggestion_form'] = SuggestionForm()
        c['image_form'] = ImageForm()
        suggestions = Suggestion.objects.all()
        c['suggestions'] = suggestions
        return c

engagement/views.py
import mimetypes

from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.views.generic import ListView
from .forms import ImageForm, SuggestionForm
from .models import Image

from flax_views.mixins import PageTitleMixin


class SuggestionCreateView(PageTitleMixin, CreateView):
    form_class = SuggestionForm
    title = 'Create Suggestion'
    template_name = 'blog/index.html'
    suggestion_form_error = False

    def get_success_url(self):
        messages.success(self.request, 'Thank you for your suggestion, we will review it and if it is viable we will'
                                       ' consider. Kindly click on the Whatsapp share button below so that we can gather as much'
                                       ' as possible information.')
        return reverse('blog:index')

    def form_invalid(self, form):
        self.suggestion_form_error = True
        return super(SuggestionCreateView, self).form_invalid(form)


    def get_context_data(self, **kwargs):
        c = super(SuggestionCreateView, self).get_context_data(**kwargs)
        c['suggestion_form_error'] = self.suggestion_form_error
        return c


class ImageCreateView(PageTitleMixin, CreateView):
    title = 'Gallery'
    form_class = ImageForm
    model = Image
    template_name = 'blog/index.html'
    image_form_error = False

    def form_valid(self, form):
        return super(ImageCreateView, self).form_valid(form)

    def form_invalid(self, form):
        self.image_form_error = True
        return super(ImageCreateView, self).form_invalid(form)


    def get_success_url(self):
        return reverse('engagement:image_list')

    def get_context_data(self, **kwargs):
        c = super(ImageCreateView, self).get_context_data(**kwargs)
        c['image_form_error'] = self.image_form_error
        return c


class ImageListView(PageTitleMixin, ListView):
    title = 'Gallery'
    model = Image
    template_name = 'blog/gallery/images.html'

templates/base.html
{% load static %}

<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>{% if title %}{{ title }} | {% endif %}Flax</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta property="og:title" content="Flax"/>
        <meta property="og:type" content="Social"/>
        <meta property="og:description" content="Technology brings us closer, Lets stay connected."/>
        <meta property="og:site_name" content="Flax"/>
        <meta property="og:url" content="http://flax.pythonanywhere.com/"/>

        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <!-- Place favicon.ico in the root directory -->

        <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'flax/css/flax.css' %}">
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'themes/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'lightbox/ekko-lightbox.min.css' %}">
        <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
    </head>
    <body>

        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        {% include 'includes/navbar.html' %}

        {% include 'includes/messages.html' %}

        {% block content %}

        {% endblock content %}

        <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.12.0.min.js"><\/script>')</script>
        <script src="{% static 'js/plugins.js' %}"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="{% static 'js/lib/jquery.easing.min.js' %}"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script src="{% static 'lightbox/ekko-lightbox.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
        <script>
            $(document).on('click', '[data-toggle="lightbox"]', function(event) {
                event.preventDefault();
                $(this).ekkoLightbox();
            });
        </script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
{#        <script>#}
{#            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=#}
{#            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;#}
{#            e=o.createElement(i);r=o.getElementsByTagName(i)[0];#}
{#            e.src='https://www.google-analytics.com/analytics.js';#}
{#            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));#}
{#            ga('create','UA-XXXXX-X','auto');ga('send','pageview');#}
{#        </script>#}
    </body>
</html>

templates/blog/gallery/images.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block content %}

    <div class="container">
        <div class="col-md-12">
            {% for image in image_list %}
            <div class="col-lg-4 col-sm-6 text-center">
                <a href="{{ image.pic.url }}" data-toggle="lightbox" data-title="{{ image.caption }}">
                    <img src="{{ image.pic.url }}" class="img-fluid img-thumbnail">
                </a>
            </div>
        {% endfor %}
        </div>
    </div>

{% endblock content %}

templates/blog/index.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_filters %}

{% block content %}

    <!-- Page Content -->

    <div class="container">

        <!-- Heading Row -->
        <div class="row">
            <div class="col-md-8">
                <img class="img-responsive img-rounded" src="{% static 'img/slides/1.jpg' %}" alt="">
            </div>
            <!-- /.col-md-8 -->
            <div class="col-md-4">
                <h1>Flax</h1>
                <p class="text-justify">Small trading center at the Border of Keiyo District and Uasin Gishu District in Rift Valley Province.
                    This is where the Flourspar mineral is loaded onto the trains to be transported to Mombasa.
                </p>
                <p>
                    <strong>Nearby town: </strong><i>Eldoret</i>
                    <br/>
                    <strong>Coordinates: </strong><i>0°22'6"N   35°28'4"E</i>
                </p>
{#                <a class="btn btn-primary btn-lg" href="#">Edit This</a>#}
            </div>
            <!-- /.col-md-4 -->
        </div>
        <!-- /.row -->

        <hr>

        <!-- Call to Action Well -->
        <div class="row">
            <div class="col-lg-12">
                <div class="well text-center">
                    get latest news, events etc etc ...
                </div>
            </div>
            <div class="col-lg-12">
                <div class="well text-center">
                    <div class="row">
                        <div class="col-sm-12">
                            <h5>
                                Share via Whatsapp
                            </h5>
                        </div>
                        <div class="col-sm-12">
                            <a href="whatsapp://send?text=http://flax.pythonanywhere.com/ hey checkout new flax website, it is still in the initial step of development, click on the link and fill the form provided. Dont forget to share"
                               class="btn btn-success"
                               data-action="share/whatsapp/share">
                                <img src="{% static 'svg/whatsapp.svg' %}" alt="Whatsapp" srcset="{% static 'svg/whatsapp.svg' %}">
                                 Whatsapp
                            </a>
                            <hr/>
                            <br/>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="page-header text-center">Help us build a website that suits everyone</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-6 suggestion">
                                <h4 class="text-center">Please fill the form below</h4>
                                <br>

                                <div class="row">
                                    <div class="col-md-12 container">
                                        <div class="alert alert-info" role="alert">
                                            <p class="text-justify">
                                                Data collected from the form below will help us develop and design this website
                                                according to your specification, so any detail that you submit is very important.
                                            </p>
                                        </div>
                                    </div>
                                </div>

                                <div class="panel-body">
                                {% if not suggestion_form_error %}
                                    <form method="post" action="{% url 'engagement:suggestion_create' %}">
                                        {% csrf_token %}
                                        {% if image_form %}
                                        {{ suggestion_form|crispy }}
                                        {% else %}
                                            {{ form|crispy }}
                                        {% endif %}
                                        <input class="btn btn-default" type="submit" value="Submit Suggestion"/>
                                    </form>
                                {% endif %}
                                </div>
                                <hr/>
                                <div class="panel-body">
                                {% if not image_form_error %}
                                    <form method="post" action="{% url 'engagement:image_create' %}" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {% if image_form %}
                                        {{ image_form|crispy }}
                                        {% else %}
                                            {{ form|crispy }}
                                        {% endif %}
                                        <input class="btn btn-default" type="submit" value="Upload Image"/>
                                    </form>
                                {% endif %}
                                </div>
                            </div>

                            <div class="col-md-6">
                                <h4 class="text-center">Submitted suggestions <span class="badge">{{ suggestions.count }}</span></h4>
                                <br>
                                <div class="panel-body">
                                    {% for suggestion in suggestions %}
                                        <div class="media well">
                                            <div class="media-left">
                                                <a href="#">
                                                    <img class="media-object" src="{% static 'img/avatar.png' %}" alt="...">
                                                </a>
                                            </div>
                                            <div class="media-body">
                                                <h4 class="media-heading">{{ suggestion.username }} <br/><small class="pull-right">{{ suggestion.timestamp|timesince }} ago</small></h4>
                                                <br/>
                                                <p class="text-justify"><i>"{{ suggestion.your_suggestion }}"</i></p>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                                <hr/>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p class="text-center">Copyright &copy; Flax Area 2017</p>
                </div>
            </div>
        </footer>

    </div>

    <!-- /.container -->

{% endblock content %}

templates/includes/messages.html
<div class="user-messages">
        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>{{ message.tags|capfirst }}!</strong> {{ message|safe }}.
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>

templates/includes/navbar.html
<!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'blog:index' %}">
                    Flax Area
                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'engagement:image_list' %}">Gallery</a>
                    </li>
{#                    <li>#}
{#                        <a href="#">Services</a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#">Contact</a>#}
{#                    </li>#}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>